### ISSUE TITLE
[BUG/FR?] Include heading relative indentation

### ISSUE THREAD

**Issue by replete** [iiz00/obsidian-daily-note-outline#18]
### Plugin settings screenshot
![Screenshot 2023-05-14 at 23 17 09](https://github.com/iiz00/obsidian-daily-note-outline/assets/812139/3cee8760-df1b-47e6-8fd3-f9e28544354d)

![Screenshot 2023-05-14 at 23 31 54](https://github.com/iiz00/obsidian-daily-note-outline/assets/812139/14d9caad-ebe9-4a81-a4e8-b64308e6c228)
(to include only content underneath this heading from the daily note)

### Screenshot of 'Notes' heading content

![Screenshot 2023-05-14 at 23 52 30](https://github.com/iiz00/obsidian-daily-note-outline/assets/812139/5c806f6d-eef9-4fbe-bb05-b8f2b0b23c30)

### Expected

I have a very long daily note with uninteresting checklists, so the include content under heading is exactly what I am looking for to compare sections of information across daily notes, but the indentation is not relative and a little unexpected.

I was expecting relative indentation, something like this:

![image](https://github.com/iiz00/obsidian-daily-note-outline/assets/812139/cee7fc6f-e44b-4235-866f-cbc812b5bb79)
(I forgot to draw the missing link in this image)

Perhaps this is a bug, or another checkbox to enable relative indentation for heading includes?

I hope this makes sense!

I am very happy to discover this plugin, thank you for doing such an excellent job - very exhaustive and useful 🙏

- Phil

**Comment by iiz00** [comment]
Is the heading `Notes` in the screenshot H3? Or is it H1 or H2?
The following assumes it is H3.  

As for the indentation of list items,
Would changing `Setting -> Appearance -> Indent other than heading" to "preparing heading +1` not result in the expected behavior?

As for the indentation of headings,
The indentation of the heading is determined by the difference between the highest level of indentation enabled in `Setting -> Headings (Heading level to display)`.
In your case, would turning off Level 1-2 or Level 1-3 not result in the expected behavior?

If you are saying that `Notes` is H1 OR H2 and should be indented one level even if there is a gap between the levels of the headings, that is a different story.

If I have misinterpreted your intent, please feel free to point it out.
Also, the explanations may be difficult to understand because of the complexity of the setting items and my English language skills. If there are any words or phrases that are difficult to understand in the explanation on the settings screen, please feel free to point them out.

**Comment by replete** [comment]
🤦‍♂️ I misunderstood the UI, I just needed to uncheck H1, H2, H3 to get the functionality I was expected. My apologies for this.

This plugin is great, thank you again for releasing such excellent work!
