### ISSUE TITLE
[FR] Ability to collapse the whole list of daily notes to enable quicker navigation

### ISSUE THREAD

**Issue by FeralFlora** [iiz00/obsidian-daily-note-outline#21]
Thanks for this great plugin. I think it would be an improvement to be able to collapse or fold all the files so only the filename / date is visible as a top level item. Then, clicking on the filename unfolds that file to reveal its content. This also implies that single files can be folded on demand by clicking the filename, without folding all the files.

**Comment by FeralFlora** [comment]
@iiz00 Sorry to ping you, but do you have any thoughts on this? Of course, it does conflict with the current behavior, which is to open the note. Therefore, it would probably be necessary to have a certain element of the heading trigger folding. This element could be the calendar icon, for example (see screenshot).

![image](https://github.com/iiz00/obsidian-daily-note-outline/assets/33608083/fe0c93a4-a37e-4802-8557-2988a6da9055)

**Comment by iiz00** [comment]
Sorry for the lack of progress. Actually, I am working on a new plugin that applies the Daily Note Outline mechanism to other regular note files. Since I implemented collapsing in that plugin, I will eventually be able to implement collapsing in DNO as well. However, it will still take some time to release the new plugin and implement folding to DNO.
I plan to add a folding icon similar to the one in the file explorer.

**Comment by FeralFlora** [comment]
No problem, thanks for the response. That new plugin sounds very interesting and useful too. No worries about the time it takes!

**Comment by iiz00** [comment]
Collapsing notes was implemented in v1.4.0.
Please try it and tell me if you have a problem😄

**Comment by FeralFlora** [comment]
> Collapsing notes was implemented in v1.4.0. Please try it and tell me if you have a problem😄

No problems, it works great. Thank you! ❤️
